languageCode = "en"
languageName = "English"
weight = 1
title = "ChemMCP"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.png"
  description = "A powerful, lightweight theme for Hugo."

[params.author]
  name = "The OSU NLP Group"
  email = "nuno@n9o.xyz"
  image = "img/osunlp_logo.jpg"
  headline = "The OSU NLP Group."
  bio = "The OSU NLP Group."
  links = [
    { x-twitter = "https://x.com/osunlp" },
    { github = "https://github.com/OSU-NLP-Group" },
  ]