# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Home"
  pageRef = "_index"
  weight = 1

[[main]]
  name = "Get Started"
  pageRef = "get-started"
  weight = 3

[[main]]
  name = "Tools"
  pageRef = "tools"
  weight = 12

[[main]]
  name = "QuickConfig"
  pageRef = "quick-config"
  weight = 13

[[main]]
  name = "Dev Guide"
  pageRef = "dev-guide"
  weight = 15

[[main]]
  name = "Related Research"
  identifier = "related-research"
  weight = 20

[[main]]
  name = "ChemToolAgent"
  parent = "related-research"
  url = "https://osu-nlp-group.github.io/ChemToolAgent/"
  weight = 21

[[main]]
  name = "LlaSMol"
  parent = "related-research"
  url = "https://osu-nlp-group.github.io/LLM4Chem/"
  weight = 22

# [[main]]
#   identifier = "twitter"
#   pre = "x-twitter"
#   url = "https://twitter.com/burufugu"
#   weight = 200

#[[main]]
#  identifier = "mastodon"
#  pre = "mastodon"
#  weight = 300
#  url = "https://masto.ai/@blowfish"

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/OSU-NLP-Group/ChemMCP"
  weight = 400

[[main]]
  identifier = "discord"
  pre = "discord"
  url = "https://discord.gg/sfZ26Qt3"
  weight = 401

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.
# 
# Note: Footer menu is now implemented directly in layouts/partials/footer.html
