name: Build & deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install uv package manager
        run: |
          # Download and run uv's official installer
          curl -LsSf https://astral.sh/uv/install.sh | sh
          # uv installs into ~/.local/bin by default, so add that to PATH
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure GitHub authentication for private deps
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Rewrite any https://github.com/ URL to include the token
          git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: Sync env, generate docs
        run: |
          source .venv/bin/activate
          uv sync
          python -m scripts.generate_tool_envs
          python -m scripts.generate_tools_doc

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Build Hugo site
        run: hugo --source site --destination site/public

      - name: Deploy to gh_pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site/public
          publish_branch: gh_pages
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com